### ISSUE TITLE
Kramdown math block not supporting `\begin{align}`?

### ISSUE THREAD

**Issue by alexfanchina** [qwtel/hydejack#101]
I'm using this great Jekyll template. Most of the math blocks in my posts work nicely, but the ones starting with LaTeX code `\begin{align}` or `\begin{case}` don't. For example, this is a sample from [the kramdown tutorial](https://kramdown.gettalong.org/syntax.html#math-blocks): 
```
$$
\begin{align*}
  & \phi(x,y) = \phi \left(\sum_{i=1}^n x_ie_i, \sum_{j=1}^n y_je_j \right)
  = \sum_{i=1}^n \sum_{j=1}^n x_i y_j \phi(e_i, e_j) = \\
  & (x_1, \ldots, x_n) \left( \begin{array}{ccc}
      \phi(e_1, e_1) & \cdots & \phi(e_1, e_n) \\
      \vdots & \ddots & \vdots \\
      \phi(e_n, e_1) & \cdots & \phi(e_n, e_n)
    \end{array} \right)
  \left( \begin{array}{c}
      y_1 \\
      \vdots \\
      y_n
    \end{array} \right)
\end{align*}
$$
```
I didn't find a way to fix this. 
## 
Plus, adding
```
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```
manually to my `.md` posts helps render the math starting with `\begin{` correctly, but it results to duplicate rendering.

**Comment by qwtel** [comment]
hi, unfortunately katex doesn’t support `align`. they recommend using `aligned` instead.
