### ISSUE TITLE
[Bug] Back button broken on iOS (v8 pro)

### ISSUE THREAD

**Issue by andrewmontoyaiv** [qwtel/hydejack#102]
Thanks for the great theme, qwtel!

On v8 pro, using the back button with safari iOS will result in a 404. Clicking back from anywhere other than the homepage resolves to` baseurl.com/^[%20/t/r/n/f]+|[%20/t/r/n/f]+$/g`. However, going forward will resolve to the right page. I tested this issue with other ios browsers (chrome, firefox, edge) and this problem only shows up again in edge.

**Comment by qwtel** [comment]
hi,

i could not reproduce this. could you be more specific about which version of ios you are using?
