### ISSUE TITLE
Error in documentation about SSH

### ISSUE THREAD

**Issue by inspectordanno** [qwtel/hydejack#103]
In the documentation regarding installing the PRO theme via Github, there is a terminal command for copying the key file to SSH:

`$ cp ~/Downloads/hydejack-pro-v8.0.0/.ssh/hydejack_8_pro ~/.ssh/`

I believe it should be

`$ cp ~/Downloads/hydejack-pro-8.0.0/.ssh/hydejack_8_pro ~/.ssh/`

The default name of the folder doesn't contain the `v` before `8.0.0`.

Thanks for this great theme!!

**Comment by qwtel** [comment]
True. thanks for reporting this. fix soon
