### ISSUE TITLE
v8 resume PDF?

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#106]
Is there supposed to be a feature to generate it, as you link to an example PDF in the docs, or is it implied that this is from printing to PDF from the html page?

**Comment by qwtel** [comment]
yes, printing the page from the html page. I wrote a lot of custom CSS to make this look good on a ~A4 paper. 

It works best with Chrome (which has options to remove clutter like page number/url), but is otherwise browser-agnostic.
