### ISSUE TITLE
Disqus comments broken (and possible fix).

### ISSUE THREAD

**Issue by Shilo** [qwtel/hydejack#107]
Disqus comments arent working. Nothing shows in the div.

In chrome, it shows the following console error:

> (index):107 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://[REMOVED FOR PRIVACY].disqus.com/admin/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

I believe the bug is in "hydejack/_includes/head/links.html" line 21:
`<link rel="dns-prefetch" href="https://{{ disqus }}.disqus.com" id="_hrefDisqus">`

I believe the fix is:
`<link rel="dns-prefetch" href="https://{{ disqus }}.disqus.com/embed.js" id="_hrefDisqus">`

I am not sure if this is the correct way to handle it since I don't know how the system works. But it works on my side.

I would love input on this and/or if this is the correct fix.

**Comment by qwtel** [comment]
it's only removed form hydejack's core .js file. 

If you look carefully the code is now located in `_includes/my-comments.html`, where it can be more easily overwritten by custom solutions.

**Comment by Shilo** [comment]
Apologizes, I didn't have time to look at all of the commit changes. Thank you for the hard work!

**Comment by rriemann** [comment]
As I understand @qwtel, you just have to copy the Disqus js code to your custom file `_includes/my-comments.html` because vanilla hydejack will not include this code for all users anymore. I think it is reasonable, as Disqus is just one choice among many and while it is popular, it is not necessarily good.

**Comment by qwtel** [comment]
> you just have to copy the Disqus js code to your custom file _includes/my-comments.html because vanilla hydejack will not include this code for all users anymore

correct

> I think it is reasonable, as Disqus is just one choice among many and while it is popular, it is not necessarily good

yes, similar to how analytics works now
