### ISSUE TITLE
8.1 breaks on netlify

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#108]
I updated to v8.1, merged in to my master branch, which triggers a deploy to netlify. Here's the relevant portion of the log:

9:27:21 AM: Installing NPM modules using NPM version 5.6.0
9:27:28 AM: npm
9:27:28 AM:  WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.6.8 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
9:27:29 AM: npm WARN
9:27:29 AM: notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.17.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
9:27:38 AM: > hydejack@8.1.0 prepare /opt/build/repo
9:27:38 AM: > npm run test && npm run clean && npm run build
9:27:38 AM: > hydejack@8.1.0 test /opt/build/repo
9:27:38 AM: > eslint _js
9:27:39 AM: /opt/build/repo/_js/src/cross-fader.js
9:27:39 AM:   102:3  error  Parsing error: Unexpected token )
9:27:39 AM: /opt/build/repo/_js/src/flip/index.js
9:27:39 AM:   36:3  error  Parsing error: Unexpected token )
9:27:39 AM: /opt/build/repo/_js/src/flip/project.js
9:27:39 AM:   25:3  error  Parsing error: Unexpected token )
9:27:39 AM: /opt/build/repo/_js/src/flip/title.js
9:27:39 AM:   72:3  error  Parsing error: Unexpected token )
9:27:39 AM: /opt/build/repo/_js/src/push-state.js
9:27:39 AM:   259:3  error  Parsing error: Unexpected token )
9:27:39 AM: ✖ 5 problems (5 errors, 0 warnings)
9:27:39 AM: npm ERR! code ELIFECYCLE
9:27:39 AM: npm ERR! errno 1
9:27:39 AM: npm ERR! hydejack@8.1.0 test: `eslint _js`
9:27:39 AM: npm ERR! Exit status 1
9:27:39 AM: npm ERR!
9:27:39 AM: npm ERR! Failed at the hydejack@8.1.0 test script.
9:27:39 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
9:27:39 AM: npm ERR! A complete log of this run can be found in:
9:27:39 AM: npm ERR!     /opt/buildhome/.npm/_logs/2018-08-21T14_27_39_434Z-debug.log
9:27:39 AM: npm ERR! code ELIFECYCLE
9:27:39 AM: npm ERR! errno 1
9:27:39 AM: npm ERR! hydejack@8.1.0 prepare: `npm run test && npm run clean && npm run build`
9:27:39 AM: npm ERR! Exit status 1
9:27:39 AM: npm ERR!
9:27:39 AM: npm ERR! Failed at the hydejack@8.1.0 prepare script.
9:27:39 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
9:27:39 AM: npm ERR! A complete log of this run can be found in:
9:27:39 AM: npm ERR!     /opt/buildhome/.npm/_logs/2018-08-21T14_27_39_569Z-debug.log
9:27:39 AM: Error during NPM install
9:27:39 AM: Error running command: Build script returned non-zero exit code: 1
9:27:39 AM: Failing build: Failed to build site
9:27:39 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
9:27:40 AM: Finished processing build request in 1m13.216151726s

**Comment by qwtel** [comment]
easiest solution would be to just get rid of package.json, as building the JS on every deploy isn't necessary (the final script is pre-built in `assets/js`).

**Comment by qwtel** [comment]
Since this seems related to ESLint, which isn't strictly speaking necessary (using Prettier for code formatting already) I'm probably going to remove it in the next release.
