### ISSUE TITLE
v8.x SASS/CSS bug?

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#109]
I just noticed that in desktop Chrome and Safari (screen shots below), that selecting the hamburger button to return to the cover page causes the first menu item (in my case, 'About') to be selected/highlighted. I don't recall this behavior in 7.x.

<img width="511" alt="chrome screenshot" src="https://user-images.githubusercontent.com/980297/44412463-9ca5f280-a52e-11e8-9aa4-24d35cfad2cb.png">
<img width="454" alt="safari screenshot" src="https://user-images.githubusercontent.com/980297/44412464-9ca5f280-a52e-11e8-955e-701873450241.png">

**Comment by qwtel** [comment]
this is an accessibility feature to help people with only keyboard input to navigate the site

**Comment by shawnyeager** [comment]
Got it. FYI, however, that for me, keyboard navigation doesn’t work. I assumed it was accessibility, initially, but thought it might be a bug when keyboard nav failed.

**Comment by qwtel** [comment]
I think you are referring to safari? I always assumed that there was an option to enable keybard nav somewhere, but maybe I should set `tabindex` on every interactive element instead...

**Comment by shawnyeager** [comment]
I’m seeing the same behavior in both Chrome and Safari desktop.



On Aug 22, 2018 at 9:59 PM, Florian Klampfer <notifications@github.com>
wrote:


I think you are referring to safari? I always assumed that there was an
option to enable keybard nav somewhere, but maybe I should set tabindex on
every interactive element instead...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/qwtel/hydejack/issues/109#issuecomment-415267108>, or mute
the thread
