### ISSUE TITLE
v8 PRO gem-based install and LinkedIn / socials

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#111]
I'm testing moving my site over to gem-based build, and minus the previously reported issue #110, the only other break that I'm seeing is that my LinkedIn link (via my `socials.yml` data file) no longer generates with the correct prepended URL fragment, `https://www.linkedin.com/in/` and now displays a generic link icon. I've changed nothing in my `socials.yml` from the .zip-file based build I have currently.

What was `https://www.linkedin.com/in/shawnyeager` is now generating as just `/shawnyeager`.

**Comment by qwtel** [comment]
Ah, again related the the limitation of gem-based themes to only consider `assets|_layouts|_includes|_sass`. You need to copy the contents of `_data` manually, specifically `_data/social.yml` in this case.

**Comment by qwtel** [comment]
twitter and email are special cases that I've included in the theme so that the theme works out of the box when using `jekyll new`
