### ISSUE TITLE
Code block goes beyond content layout

### ISSUE THREAD

**Issue by LazyRen** [qwtel/hydejack#112]
<img width="1920" alt="screen shot 2018-08-22 at 3 31 33 pm" src="https://user-images.githubusercontent.com/8989837/44494444-9a23c580-a620-11e8-9f32-d357664bbfed.png">

As you can see with "jekyll new ..." or "gem ....",

code block goes beyond content layout till the end of right side of the web.

If this can be fixed like {:.message} on **NOTE** block stays within content layout. Would look great.

Thank you for such a great theme by the way.

**Comment by qwtel** [comment]
this is intended. 

limiting line lengths in free text improves readability of the text, but does the opposite for code  snippets. that being said, you can set the `no_break_layout` option in the config file to achieve the look you want
