### ISSUE TITLE
Page build warning regarding theme

### ISSUE THREAD

**Issue by inspectordanno** [qwtel/hydejack#113]
I got this email notification from github:

The page build completed successfully, but returned the following warning for the `master` branch:

You are attempting to use a Jekyll theme, "jekyll-theme-hydejack-pro", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

---

In `_config.yml`, in the theme section, I have:
`theme: jekyll-theme-hydejack-pro`

There is also
`remote_theme: qwtel/hydejack`
But that is commented out.

Should I comment out `theme` and uncomment `remote_theme`?

EDIT: This is in my gemfile
`gem "jekyll-theme-hydejack-pro", git: 'git@hydejack:qwtel/hydejack-8-pro.git'`
(I installed the theme via the PRO via Github option in the documentation.)
Should I uncomment the remote_theme or should I leave it as is?

**Comment by qwtel** [comment]
Unfortunately, neither `theme` nor `remote_theme` works with the PRO gem on GitHub Pages. You'll have to include the source files in the repository.

**Comment by inspectordanno** [comment]
Ah, ok got it. So I just commented them both out.

But I can still upgrade via gem, correct?
`bundle update jekyll-theme-hydejack-pro`

**Comment by qwtel** [comment]
If you build locally, yes.

**Comment by inspectordanno** [comment]
Cool, thanks!

**Comment by gerdm** [comment]
> Unfortunately, neither `theme` nor `remote_theme` works with the PRO gem on GitHub Pages. You'll have to include the source files in the repository.
> 
> Alternatively, you can build locally and push the HTML files to github.

How do I go about pushing the HTML files to GitHub? I have tried to push `vendor` and `_site`, but they do not work.

Is the `remote_theme ` option still not available?

Thanks!

**Comment by qwtel** [comment]
> Is the `remote_theme` option still not available?

This is not possible and would require changes to `jekyll-remote-theme` and GitHub Pages that are outside of my control.

> How do I go about pushing the HTML files to GitHub?

~~~bash
$ cd _site
$ git init
$ git remote add origin <github_remote_url> 
$ git add .
$ git commit -m "Build"
$ git push origin master:<remote_branch>
$ cd ..
~~~
