### ISSUE TITLE
Two features that would be really helpful

### ISSUE THREAD

**Issue by inspectordanno** [qwtel/hydejack#114]
Sorry if I keep buggin you qwtel! You've been nothing but helpful to me, I really appreciate it.

There are two features that I would really like to have, and I'm not sure how to implement them, maybe they could be provided in the next version?

1. In the welcome layout, I would love if there was an option for the sidebar to be fully opened on mobile, but not on desktop. Maybe it could be called `cover: mobile_only ` or something.

2. On a project page, could there be a `url:` option for the image? I like the title url pairs, but I think some users expect to click the image and have it redirect them to the actual project.

Thanks and let me know if this would be possible to implement.

**Comment by qwtel** [comment]
I'm afraid you'll have to implement these yourself. I don't see them applicable to a general audience.
