### ISSUE TITLE
8.1 mobile problem

### ISSUE THREAD

**Issue by hx57** [qwtel/hydejack#115]
Hello, I installed 8.1 and it works great in desktop browser but on mobile, doesnt matter where I click, it always goes to index.md. https://hx57.io Any ideas?

**Comment by qwtel** [comment]
can’t reproduce, probabaly related to browser/os.

**Comment by hx57** [comment]
iPhone OS: 10.3.3 -> Chrome 67.0.3396.87, Safari 

Both mobile browsers produce same behavior, upon landing, doesnt matter where you click, it will only go to index.md

**Comment by qwtel** [comment]
ah i see. iOS 10 has some issues. i’ve started working on a fix but it got very complicated. maybe will revisit in the future.

disabling the drawer should prevent the issue if iOS 10 is a priority.
