### ISSUE TITLE
Feature request: options for dark mode color

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#120]
Love the dark mode option, but in my particular case the greenish-gray background color for dark mode clashes badly with my highlight/sidebar (blue to purple gradient) colors. Would it be possible to semi-intelligently or even manually be able to select a dark mode color that better works with various highlight colors?

Thanks.

**Comment by qwtel** [comment]
set theme_color, will adjust the gray slightly

**Comment by shawnyeager** [comment]
Only slightly, but it still limits usability of the dark mode feature unless chosen accent_color happens to work with that greenish grey.
