### ISSUE TITLE
Sitemap,Leverage Browser cache,

### ISSUE THREAD

**Issue by dkarthe** [qwtel/hydejack#124]
HI,
first of all Thanks for making Hydejack, its really ultrafast. and am a freelancer, am not a developer. some of issues occurs in my site. so kindly tell me clearly..  
1.In my site, If I am adding a new post the sitemap can't automatically generate. every time I had manually update sitemap file.
2.How to eliminate render-blocking JavaScript and CSS in above-the-fold content
3.How to reduce Leverage browser cache. 

Thanks in advance.

**Comment by qwtel** [comment]
Sorry, these are service requests, not issues with the theme.
