### ISSUE TITLE
Modifying <title> for home.html layout

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#126]
Is there a clean or preferred way to have a different `<title>` tag on the homepage (`index.md`) than the `title` in the front matter?

Example: the `H1` on `index.md` shows "Welcome", while the `<title>` of the page (for search indexing, etc.) simply shows the site name without appending ": Welcome"?

**Comment by shawnyeager** [comment]
Solved. Just exclude `title` in the front matter.

**Comment by qwtel** [comment]
This is not supported by Hydejack right now. It is either set by `jekyll-seo-tag` when present, or a fallback mechanism when it's not, both of which refer to `site.title`.
