### ISSUE TITLE
jekyll-seo-tag and images in hydejack

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#130]
Question: is hydejack designed to generate social meta tags for `image` automagically, or do we still need to explicity declare `image: /assets/img.jpg` in the YAML front matter?

And in lieu of either, shouldn't I be seeing `logo` from `_config.yml` used as the default in social cards?

**Comment by qwtel** [comment]
you need to declare `mage: /assets/img.jpg` in the front matter. this is part of [`jekyll-seo-tag`](github.com/jekyll/jekyll-seo-tag), not Hydejack though.
