### ISSUE TITLE
Help changing favicon and removing footer

### ISSUE THREAD

**Issue by shrvenkataraman** [qwtel/hydejack#134]
Hi, 

I am Shravan from India. I have used your hydejack-starter-kit to create my github site - 
shrvenkataraman.github.io

I am facing two problems.

1. Removing footer text/copyright and hydejack website link on footer - I don't know where it fetches the info from. Went through the entire code, couldn't find the place. (The place where it was located on hydejack theme is straightforward. But hydejack-starter-kit is probably fetching that from somewhere else? Please help in this regard).

2. In hydejack-starter-kit, by default, it's showing HY favicon. There's no favicon file though, in the assets/images folder. How do i change the favicon?

Please let me know.

**Comment by qwtel** [comment]
to overwrite default icons, create the same folder structure and image files of the same name/format/size there (`/assets/icons/`). See here for filenames: https://github.com/qwtel/hydejack/tree/master/assets/icons
