### ISSUE TITLE
Removing Powered By text in Hydejack-starter-kit

### ISSUE THREAD

**Issue by shrvenkataraman** [qwtel/hydejack#135]
How to remove Powered By Hydejack v8.1.1 in the starter kit footer?

**Comment by LazyRen** [comment]
There is a 'footer.html' in {root folder}/_includes/body folder.
Comment out or remove line containing
`<p><small>Powered by <a class="external" href="https://hydejack.com/">Hydejack</a> v<span id="_version">8.1.1</span></small></p>`

**Comment by qwtel** [comment]
Not possible. I've put it there on purpose. You can remove it if you use the source files directly.
