### ISSUE TITLE
table of contents click animation is not work for none-English content

### ISSUE THREAD

**Issue by ForelaxX** [qwtel/hydejack#138]
First of all, I appreciate the hydejack theme because it's very elegant, thx a lot for your great work!
I'm using hydejack v8.1.1, when I try the toc tag, I find the toc click animation only work for the English content, and here is the none-English example:
https://forelax.space/2018/12/21/why-we-use-rvm-and-bundler.html#ruby-%E6%B5%8B%E8%AF%95

I have tried to resolve this bug but failed, I can't find the correct js file related to this animation. Maybe it is push-state.js ? I' not sure.

**Comment by ForelaxX** [comment]
I found out the key of this bug.This is a bug in hy-push-state. I have try a PR here:
https://github.com/qwtel/hy-push-state/pull/4

**Comment by ForelaxX** [comment]
@qwtel can u see this PR? https://forelax.space/2018/12/21/why-we-use-rvm-and-bundler.html#ruby-%E6%B5%8B%E8%AF%95

**Comment by qwtel** [comment]
thanks again for digging into this, fixed in v8.2.0
