### ISSUE TITLE
pro: repository not found (v8)

### ISSUE THREAD

**Issue by rriemann** [qwtel/hydejack#147]
Hello,

I try to upgrade my pro installation from 7.x to 8.x. I use the theme gem.

When I add like said in the documentation at https://hydejack.com/docs/install/#via-gem

    gem "jekyll-theme-hydejack-pro", git: 'git@hydejack:qwtel/hydejack-8-pro.git'

, then I get this error upon `bundle update`:

```
Retrying `git clone 'git@hydejack:qwtel/hydejack-8-pro.git' "/home/rriemann/.rvm/gems/ruby-2.4.3/cache/bundler/git/hydejack-8-pro-2c7a7ef09c6ec48ad168e0f0928704a49f6af16b" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@hydejack:qwtel/hydejack-8-pro.git' "/home/rriemann/.rvm/gems/ruby-2.4.3/cache/bundler/git/hydejack-8-pro-2c7a7ef09c6ec48ad168e0f0928704a49f6af16b" --bare --no-hardlinks --quiet` in directory /home/rriemann/x has failed.ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Running `git clone git@hydejack:qwtel/hydejack-pro.git`works without errors.

Git error: command `git clone 'git@hydejack:qwtel/hydejack-8-pro.git'
"/home/rriemann/.rvm/gems/ruby-2.4.3/cache/bundler/git/hydejack-8-pro-2c7a7ef09c6ec48ad168e0f0928704a49f6af16b" --bare --no-hardlinks --quiet` in directory
/home/rriemann/x has failed.
```

Running `git clone git@hydejack:qwtel/hydejack-pro.git` works without errors.

**Comment by MilovanTomasevic** [comment]
I also have a similar problem:

```sh
mt@mt:~/Dropbox/WWW/mt.fis$ bundle update
Fetching git@hydejack:qwtel/hydejack-8-pro.git
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
mt@mt:~/Dropbox/WWW/mt.fis$
```

But other options don`t work for me:

```sh
mt@mt:~/Dropbox/WWW/v8$ git clone git@hydejack:qwtel/hydejack-pro.git
Cloning into 'hydejack-pro'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by rriemann** [comment]
@MilovanTomasevic , please check if you have setup the authentication as a pro user as documented in <https://hydejack.com/docs/install/#pro-via-github-advanced>.

Please test with `ssh -v hydejack` and look for the following output:

```
Connecting to github.com
[…]
Will attempt key: /home/rriemann/.ssh/hydejack_pro_customers  explicit
```

If this does not work, consider open a separate issue.

**Comment by MilovanTomasevic** [comment]
@rriemann 
Thank you very much, but I have solved my problem, it was not a problem on the network, whether it was to the port or not - I do not know, but I solved it. Certainly thanks a lot! It works all of the time but I have not been able to wipe my comment because I have a lot of work to do.

**Comment by qwtel** [comment]
Thanks for helping out @rriemann. The whole SSH thing is basically a hack, I should make that clearer in the docs.

**Comment by yejunantonylee** [comment]
> Hello,
> 
> I try to upgrade my pro installation from 7.x to 8.x. I use the theme gem.
> 
> When I add like said in the documentation at https://hydejack.com/docs/install/#via-gem
> 
> ```
> gem "jekyll-theme-hydejack-pro", git: 'git@hydejack:qwtel/hydejack-8-pro.git'
> ```
> 
> , then I get this error upon `bundle update`:
> 
> ```
> Retrying `git clone 'git@hydejack:qwtel/hydejack-8-pro.git' "/home/rriemann/.rvm/gems/ruby-2.4.3/cache/bundler/git/hydejack-8-pro-2c7a7ef09c6ec48ad168e0f0928704a49f6af16b" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@hydejack:qwtel/hydejack-8-pro.git' "/home/rriemann/.rvm/gems/ruby-2.4.3/cache/bundler/git/hydejack-8-pro-2c7a7ef09c6ec48ad168e0f0928704a49f6af16b" --bare --no-hardlinks --quiet` in directory /home/rriemann/x has failed.ERROR: Repository not found.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 
> Running `git clone git@hydejack:qwtel/hydejack-pro.git`works without errors.
> 
> Git error: command `git clone 'git@hydejack:qwtel/hydejack-8-pro.git'
> "/home/rriemann/.rvm/gems/ruby-2.4.3/cache/bundler/git/hydejack-8-pro-2c7a7ef09c6ec48ad168e0f0928704a49f6af16b" --bare --no-hardlinks --quiet` in directory
> /home/rriemann/x has failed.
> ```
> 
> Running `git clone git@hydejack:qwtel/hydejack-pro.git` works without errors.

I am having the same issue. Could you please share how you were able to resolve this? Thanks!

**Comment by yejunantonylee** [comment]
@rriemann @MilovanTomasevic I am having the same issue. Could you please share how you were able to resolve this? Thanks!
