### ISSUE TITLE
How can change order of 'post' layout

### ISSUE THREAD

**Issue by po9357** [qwtel/hydejack#148]
I want to change order of post layout.
basic : content - about - related posts - comments 
to 
content - comments - realted posts - (about)

how can change?

**Comment by PietroPasotti** [comment]
edit your /_layouts/post.html file
not sure about where the comments come in, but:
```
{% for addon in addons %}
  {% case addon %}
  {% when 'about' %}
     {% include components/about.html %}
  {% when 'related' %}
    {% include components/related-posts.html post=post %}
  {% else %}
  {% endcase %}
{% endfor %}
```
just swap the 'when' cases to order them however you like.

**Comment by qwtel** [comment]
Changing the order of comments in not possible with configuration.
