### ISSUE TITLE
Upgrade to Pro resulting in failed page build

### ISSUE THREAD

**Issue by ianpcook** [qwtel/hydejack#149]
I purchased the Pro version, and received the ZIP file. 

I unzipped the file, copied the contents of the Upgrade folder into my local repository, then push the changes to Github. NOTE: I'm doing this on a "fresh" fork of the Hydejack repo, so there should be no problem with overwriting my own edits. 

The push to Github resulted in a failed page build email from Github, with this content: 

`The page build failed for the master branch with the following error: A file was included in /_layouts/post.html that is a symlink or does not exist in your _includes directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink/.'`

I looked at the contents of `post.html` and verified that every file listed there is present in the `_includes` directory: 

post.html: 
`{% include components/post.html post=page no_link_title=true no_excerpt=true hide_image=page.hide_image %}

{% assign addons = page.addons | default:site.hydejack.post_addons %}
{% unless addons %}{% assign addons = "about,newsletter,related,random" | split:"," %}{% endunless %}
{% for addon in addons %}
  {% case addon %}
  {% when 'about' %}
     {% include _includes/components/about.html %}
  {% when 'newsletter' %}
    {% include _includes/pro/newsletter.html %}
  {% when 'related' %}
    {% include _includes/components/related-posts.html post=post %}
  {% when 'random' %}
    {% include _includes/pro/random-posts.html post=post %}
  {% else %}
  {% endcase %}
{% endfor %}`

And the contents of _includes: 

\| => ls -LR _includes
body			head			icon-github.html	my-head.html		scripts			styles
components		header.txt		my-body.html		pro			smart-url.txt		templates

_includes/body:
analytics.html	comments.html	footer.html	index.html	main.html	menu.html	nav.html	scripts.html	sidebar.html

_includes/components:
about.html		avatar-tag.html		header.txt		icon-github.html	message.html		my-comments.html	my-scripts.html		post-list-item.html	related-posts.html	smart-url.txt		social.html
author.html		from-to.html		hy-img.html		link.html		my-body.html		my-head.html		pagination.html		post.html		scripts.html		social-list-item.html	tag-list.html

_includes/head:
feed-tag.html		index.html		links.html		meta.html		page-style.html		scripts.html		seo-fallback.html	seo-tag.html		styles.html

_includes/pro:
newsletter.html		other-projects.html	project-card.html	random-posts.html	resume

_includes/pro/resume:
awards.html		education.html		interests.html		profiles.html		references.html		volunteer.html
basics.html		header.html		languages.html		publications.html	skills.html		work.html

_includes/scripts:
cssrelpreload.min.js	load-js.js		load-js.min.js		loadCSS.min.js

_includes/styles:
inline.scss	pro		style.scss

_includes/styles/pro:
projects.scss	resume.scss

_includes/templates:
animation.html	back.html	error.html	index.html	loading.html	permalink.html	pro

_includes/templates/pro:
cookies-banner.html	dark-mode.html`

What am I doing wrong?
Thanks!

**Comment by qwtel** [comment]
Just setup a new repository with the 8.2.0 version and it built on GitHub pages without problem.

**Comment by qwtel** [comment]
Ah, I've been able to reproduce your issue. You have to put the *contents* of the `install` folder in the root of the repository!
