### ISSUE TITLE
Add resume page

### ISSUE THREAD

**Issue by RobbiNespu** [qwtel/hydejack#15]
How to have resume page like your? (https://qwtel.com/resume/)

**Comment by qwtel** [comment]
Hi, thanks for your interest.

Resume pages (together with projects and welcome pages) will be part of a "PRO" version of the theme. It will be around $30 but isn't available just now. If you want it now and can make payments via paypal or some digital currency (ether, ripple, etc) you can shoot me an email (f.klampfer@gmail.com) and I'll make you a deal.

If you don't want to spend any money, you could use the [JSON resume editor](http://registry.jsonresume.org/) to generate a resume from one of the available designs, then copy to raw HTML and CSS into a `page` layout, ie create a `resume.html` with

```
---
layout: page
title: Resume
menu: true
---

<style><insert raw CSS here></style>
<insert raw HTML here>
```

It should work, but it's tedious and won't look as nice ;)

**Comment by RobbiNespu** [comment]
Thanks! Looking when it available later
