### ISSUE TITLE
Site takes ages to generate

### ISSUE THREAD

**Issue by PietroPasotti** [qwtel/hydejack#151]
I am setting up a website using the hydejack template and no other plugins.
I am new to ruby and liquid.
My blog has about 7000 posts, and as soon as I try to generate the website on localhost, I hit a performance bottleneck. With 10 posts, it takes some 4 seconds. With 100 posts, one minute and a half. With 1000, it takes longer than my patience lasts (more than 30m).
Each post is 50 lines of text tops, and the machine I am using is an 8-core really good laptop, so I don't think that is the issue.

Can you give me any pointers on how to speed things up? What is taking all this time?

**Comment by qwtel** [comment]
Hi,

Hydejack was designed with small (~100 pages) personal sites in mind, so I haven't’ paid too much attention to performance.

The most obvious CPU hog is the inlining of the CSS on every page. You can disable it by setting 

hydejack:
  no_inline_css: true

in config.yml. This will decrease page load speed, but increase build speed dramatically.

There are a few more optimisations I could add, but I think 7000 posts will always take a couple of minutes for a full build, even with a simpler theme than Hydejack (could you confirm this?; I would also like to know how much of a difference the no_inline_css option makes). 

> Each post is 50 lines of text tops

The length of the posts doesn’t matter as much as the number of pages. 

>  the machine I am using is an 8-core really good laptop

I don’t think that Jekyll takes advantage of multi-cpu architecture. 

Are you aware of the --incremental option? You can use this for quicker previews. 

If build speed is a concern, you could look at Hugo <https://gohugo.io/>, which brands itself as the “The world’s fastest framework for building websites”. However, there is no port of Hydejack for Hugo.

Best,
Florian

**Comment by qwtel** [comment]
I've added some new options in v8.3.0 and also wrote about improving building speeds: https://hydejack.com/blog/hydejack/2019-02-18-improving-site-build-speed/

**Comment by PietroPasotti** [comment]
Update: --incremental flag did not help at all.
Also disabling the inlining of css did not make much of a difference.

Increasing the number of posts per page (pagination setting) on the other hand, decreased the build time from two hours to 40 minutes. Almost usable.

**Comment by qwtel** [comment]
I've been able to get it to build on GH Pages without timeout [here](https://github.com/qwtel/PietroPasotti).

Make sure you 
* use the latest version of Hydejack (>8.3.0) via `remote_theme` if you want to build on GH Pages
* don't keep any of the old Hydejack files in the repository
* set `use_lsi`, `no_inline_css`, and `no_page_style` to `true`

**Comment by PietroPasotti** [comment]
Nice! Thanks a lot for the help :) 
Questions:
what do you mean by old HJ files? Like, I should start with a fresh install?
what do the use_lsi and no_page_style flags entail?

**Comment by qwtel** [comment]
See the updated version of the [article](https://hydejack.com/blog/hydejack/2019-02-18-improving-site-build-speed/) to see what the options are doing.

**Comment by qwtel** [comment]
> what do you mean by old HJ files?

There were source files in the repo. I've cleaned them up and used the theme via `jekyll-remote-theme` instead. The easiest way to clean it up is by starting with a fresh install, sure.
