### ISSUE TITLE
Old version via remote?

### ISSUE THREAD

**Issue by luni64** [qwtel/hydejack#152]
If I use _remote_theme_ I get an older version 
```
# Theme
# ---------------------------------------------------------------------------------------

#theme: jekyll-theme-hydejack
remote_theme: qwtel/hydejack@gem
```
![image](https://user-images.githubusercontent.com/12611497/53694119-62a18d00-3daa-11e9-9a39-01c74f717fe2.png)

With ` theme: jekyll-theme-hydejack` I get the current version. 

Any chance to get the current version via remote? (Or any other method to use the current version on github-pages?

**Comment by qwtel** [comment]
Remove the @gem in the end 😉

**Comment by luni64** [comment]
Thanks that works
