### ISSUE TITLE
Font Awesome Icons

### ISSUE THREAD

**Issue by BetaLeaf** [qwtel/hydejack#155]
I want to use font awesome icons to implement some custom social badges, however, because this theme is using <span> instead of <i> or <svg> on social icons, font awesome icons fail to load. Is there an easy way to get Font Awesome to work? I'm still very new to Jekyll so I appreciate your patience while I am learning everything.

**Comment by qwtel** [comment]
If you have to individual svg files of the icons you want to add, you can try following this guide: https://hydejack.com/docs/advanced/#adding-a-custom-social-media-icon

**Comment by BetaLeaf** [comment]
Thanks
