### ISSUE TITLE
Feed on categories

### ISSUE THREAD

**Issue by RobbiNespu** [qwtel/hydejack#16]
Hi there, seem the only available feed are the default which `domain.com/feed.xml`
Are there is anyway to get feed by  categories? If found it not available on this theme. Need that for aggregator on specific topics

Example : [http://rhea-ayase.eu/categories/feed-life.xml](http://rhea-ayase.eu/categories/feed-life.xml)

**Comment by qwtel** [comment]
I'm afraid the [Jekyll Feed Plugin](https://github.com/jekyll/jekyll-feed) does not support this.

You could remove it and render multiple `feed-<category>.xml` files yourself, using the [plugin's template](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml), but getting the posts like 

```
{% assign category = site.featured_categories | where: "slug", "<your-category>" | first %}
{% assign posts = site.categories[page.slug] %}
```

**Comment by RobbiNespu** [comment]
Found my own hack. Create a `/feed/` directory on root then add manually what tag/category you want. I use tag "personal" for example, named and saved as `/feed/feed.personal.xml` :
```
---
---

<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
 <channel>
  <title>{{ site.title  | xml_escape }} - blog</title>
  <description>Posts tagged as 'blog'</description>
     <atom:link href="{{ site.url }}/feed/feed.personal.xml" rel="self" type="application/rss+xml" />
  <link>{{ site.url }}/tag/personal/</link>
  <updated>{{ site.time | date_to_xmlschema }}</updated>
  <author>
   <name>{{ site.author.name }}</name>
   <email>{{ site.author.email }}</email>
  </author>

  {% for post in site.tags.personal limit:10 %}
   <item>
    <title>{{ post.title | xml_escape }}</title>
    <description>{{ post.content | xml_escape }}</description>
    <link>{{ site.url }}{{ post.url }} </link>
    <pubDate>{{ post.date | date_to_xmlschema }}</pubDate>
    <guid isPermaLink="true">{{ site.url }}{{ post.url }}</guid>
   </item>
  {% endfor %}
 </channel>
</rss>

```

Jekyll will automatic generated you feed.

Result : https://robbinespu.github.io/feed/feed.personal.xml
