### ISSUE TITLE
Option for full content post or read more post excerpt on the main page

### ISSUE THREAD

**Issue by RobbiNespu** [qwtel/hydejack#17]
Can i have feature for full post on my main page as previous version ? So I can decide which post will have short intro with "read more" or post with full content. The default now is, all post are post excerpts on the front.

If you don't get what I mean. I hope, there is a feature like https://codex.wordpress.org/Customizing_the_Read_More

**Comment by qwtel** [comment]
This should already work, see the [Jekyll documentation](https://jekyllrb.com/docs/posts/#post-excerpts).
