### ISSUE TITLE
Displaying/linking to PDFs

### ISSUE THREAD

**Issue by bioboot** [qwtel/hydejack#25]
Awesome theme, thank you so very much for making it available!  

I am having problems on the latest chrome and safari for mac loading linked PDF files.

I am using a bit of markdown code like this on a freshly cloned repo:

`Link to a PDF [here]({{ site.baseurl }}/BGGN213_F17_syllabus.pdf).
`

When served up and you click on the link it hangs in a loading like state on both browsers (sidebar still shows with a blank right hand side little loading icon). If you refresh the page the PDF displays fine.

Am I doing something wrong?
Thanks again!

**Comment by qwtel** [comment]
Glad you like it. If you want to support me, consider buying the PRO version 😄 

What you can do is add the `no-push-state` class to the link.
kramdown has built-in syntax for this is:

```md
[here]({{ site.baseurl }}/BGGN213_F17_syllabus.pdf){:.no-push-state}
```

**Comment by qwtel** [comment]
Thank you!

That's an interesting use-case. I haven't seen a version of Hydejack with quite so much content so far 👍 

Just one random observation: kramdown has built-in syntax and Hydejack has styling for 
"definition lists" (`<dl/>` html tag), so there would be a nicer way to display the staff data without having to fiddle with spaces:

~~~
Course Director
: [Prof. Barry J. Grant](http://thegrantlab.org/) (Email: [bjgrant@ucsd.edu](mailto:bjgrant@ucsd.edu))

Instructional Assistant
: [Ileena Mitra](https://bioboot.github.io/bggn213_f17/ileenamitra@eng.ucsd.edu) (Email: [ileenamitra@eng.ucsd.edu](mailto:ileenamitra@eng.ucsd.edu))

Course Syllabus
: [Fall 2017 (PDF)](https://bioboot.github.io/bggn213_f17/class-material/BGGN213_F17_syllabus.pdf){:.no-push-state}

~~~

I wasn't aware of the language thing, I should definitely change it. Thanks for pointing that out!

**Comment by bioboot** [comment]
Very nice, thank you for the tip!  

Quick question: How could I put this "definition list" code sniper in the "author.about" field from the `_data/authors.yml` file without getting an error:

`Error: (play/_data/authors.yml): could not find expected ':' while scanning a simple key at line 11 column 1`

**Comment by qwtel** [comment]
Use `|` and make sure you indent with the correct amount of spaces (looks like you have to fiddle with spaces after all)
```yml
  about: |
    A paragraph.

    Term1
    : Definition1

    Term2
    : Definition2
```
