### ISSUE TITLE
Can't have quotation marks (") as the first character in caption tag

### ISSUE THREAD

**Issue by imswebra** [qwtel/hydejack#28]
When creating a project, if there is a quotation mark as the first character in the caption, Jekyll will provide an error.

Using the documentation example, we can see that the following works fine.

```
---
layout: project
title: Hyde v2*
date: 2 Jan 2014
screenshot:
  src: /hydejack/assets/img/projects/hyde-v2@0,25x.jpg
  srcset:
    1920w: /hydejack/assets/img/projects/hyde-v2.jpg
    960w: /hydejack/assets/img/projects/hyde-v2@0,5x.jpg
    480w: /hydejack/assets/img/projects/hyde-v2@0,25x.jpg
caption: Hyde is a brazen two-column Jekyll theme.
description: >
  Hyde is a brazen two-column [Jekyll](http://jekyllrb.com) theme that pairs a prominent sidebar with uncomplicated content. It's based on [Poole](http://getpoole.com), the Jekyll butler.
links:
  -
    title: Demo
    url: http://hyde.getpoole.com
  -
    title: Source
    url: https://github.com/poole/hyde
author: mdo
---
```

However, if we change the `caption:` tag to `caption: "Hyde is ...`, (shortened for readability) we get the following error:

```
Error: could not read file [file location]/[file name]: (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 11 column 10
```

This is an appropriate error message, indicating the correct position of the fraudulent quotation mark. **However,** if we use the quotation mark in a more realistic sense, changing `caption: "Hyde is ...` to `caption: "Hyde" is ...` (note the new, closing quotation mark) we get the following error that does not indicate the correct position of the error.

```
Error: could not read file [file location]/[file name]: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
```

If this cannot be fixed, it should at least be included in the documentation IMO, simply due to the difficulty in finding the error.

**Comment by qwtel** [comment]
Hi, thanks for taking time for reporting this, however this is not related to Hydejack, its simply a misunderstanding of how YAML works. 

This works fine (escaping quotes)

```yaml
caption: \"Hyde\" is a brazen two-column Jekyll theme.
```

so does this (wrapping in single quotes)
```yaml
caption: '"Hyde" is a brazen two-column Jekyll theme.'
```
and this (using block string without newlines)
```yaml
caption: |
  "Hyde" is a brazen two-column Jekyll theme.
```
YAML has diffrent ways of handling strings, you should check out the various tutorials around the web if you want to know more.
