### ISSUE TITLE
Change theme for code syntax highlighting

### ISSUE THREAD

**Issue by BigChief45** [qwtel/hydejack#29]
Is it possible to change the theme of the syntax highlighting for code blocks? For example, changing it to Monokai, Molokai, etc. etc.

**Comment by qwtel** [comment]
yes, just change this file: https://github.com/qwtel/hydejack/blob/master/_sass/_syntax.scss

if you are using the gem, create `_sass/_syntax.scss` to override it

**Comment by BigChief45** [comment]
Thanks!
