### ISSUE TITLE
Remove "Table of Contents" from TOC itself

### ISSUE THREAD

**Issue by janpio** [qwtel/hydejack#30]
I noticed the documentation including "Table of Contents" as the first item in the TOC itself: e.g. https://qwtel.com/hydejack/docs/6.6.1/configuration/

Kramdown has a way to exclude headlines from the TOC:

`{:.no_toc}`

Source: https://kramdown.gettalong.org/converter/html.html#toc

Interested in using this in the docs? I could create a quick PR.

**Comment by qwtel** [comment]
Cool, I wasn't aware of that. No need for a PR, current code is waaay out of sync with what I have in the private repo. Will include it in the next release, thanks!

**Comment by janpio** [comment]
You can't mention a "next release" and not give a hint for an ETA ;)

(Seriously, I might want to customize hydejack a bit, see #31, should I wait or go ahead with the current code base?)

**Comment by qwtel** [comment]
ETA is 2 months ago 😐 Hopefully within the next 2 months.

Regarding customization, it depends on how far you want to go.

- None of the customization options in the config file will go away, so you are safe there.
- If you've put custom code or CSS in the `my-*` type files, they will continue be included, however if it depends on internal CSS class names or ids, there *may* be problems.
- The way CSS is organized will change completely. If you modify the `scss` files (other than `my-style.scss` you will not be able upgrade smoothly.
- The drawer and 'hot reloading'  is currently handled by separate components (`y-drawer` and `y-push-state`, respectively), which will be completely rewritten.
- `_layouts`, `_includes` will change.

I should also note that the next release will be under a more restrictive GPL-3.0 license, so in case you don't want to open-source any changes you make under the same license, you might not want to wait at all.
