### ISSUE TITLE
Lanyon style header + sidebar?

### ISSUE THREAD

**Issue by janpio** [qwtel/hydejack#31]
[Lanyon](http://lanyon.getpoole.com/) was one of the original "implementations" of Poole, similar to [Hyde](http://hyde.getpoole.com/) which this template is based on. 

Has anyone already modified Hydejack to to have a Lanyon style header and sidebar? 

This would probably mean to center the main page content, add a header, show the burger all the time (and optionally make the opened menu push the page content instead of overlaying it).

**Comment by qwtel** [comment]
Not that I'm aware of. 

It would be cool to make lanyon work the "hydejack"-way with push state, etc (in fact, it would be cool to do that to arbitrary Jekyll themes, but lanyon would be the obvious starting point).
Pushing content to the side wouldn't be too much work to add to my drawer implementation.

FYI, the content in Hydejack already is centered on larger screens:

![screen shot 2017-09-09 at 08 06 33 2](https://user-images.githubusercontent.com/951987/30237639-749e3cb0-9536-11e7-8cee-ede3e7cb69db.png)

I could reconsider how Hydejack scales across lower resolutions, but that's not a priority right now.

Anyway, thanks for your input, I'll definitely keep it in mind.

**Comment by janpio** [comment]
Oh I didn't notice, my resolution is exactly at that break point it seems. <kbd>Ctrl</kbd> + <kbd>-</kbd> enabled me to see this.

Ok great, so I "only" would have to mess with the sidebar (hidden by default) and the smaller resolutions.

**Comment by qwtel** [comment]
Break points are handled here:

* https://github.com/qwtel/hydejack/blob/master/_sass/hydejack/_content-inline.scss
* https://github.com/qwtel/hydejack/blob/master/_sass/hydejack/_drawer-inline.scss

You'd also have to get rid of the media query in 

* https://github.com/qwtel/hydejack/blob/master/_js/src/drawer.js

and re-build the js (you'll have to pull in the entire node/js toolchain)

Good luck.
