### ISSUE TITLE
Including a link to a blog page in sidebar creates multiple links for blog pages!

### ISSUE THREAD

**Issue by SomuSysAdmin** [qwtel/hydejack#33]
Hey, @qwtel love your work - it's the perfect theme to customize for a noob and poor student like me!

However, I'm facing an odd problem. Look at [this](https://i.imgur.com/iplkbye.png).

Agian, owing to the fact that I'm a poor student who couldn't afford your pro version, I'm just trying to recreate the blog from scratch. Everything is working perfectly, except, I created a separate folder called `article` that contains an index.html containing the following code:

```markdown
---
layout 	: blog
title 	: Articles
menu	: true
order	: 1
---
```

If what I'm inferring is right, the `jekyll-paginate` module has ensured that any page using the format of `article/index.html`, will be created with the exact same format. Thus, when `jekyll-paginate` creates pages such as `article/page/2`, `article/page/3` and so on, each get their own separate link in the sidebar.

I really need to control this behavior. How can I fix it? Please help!!

**Comment by qwtel** [comment]
Hi, haha no problem. If you include the "powered by Hydejack" (or mention it on your about page, etc) I'm more than happy. And if you don't, well, who's gonna stop ya? 😄 

Yes, this problem keeps coming up. The pagination replicates the blog.html file and each page gets its own entry in the sidebar. There is a simple workaround. Make a `article.md` file in the root with

```
---
title: Articles
menu: true
order: 1
---
```

and remove `menu` and `order` from `articles/index.html`.

**Comment by SomuSysAdmin** [comment]
@qwtel that's genius Bro! 

Also, since I'm editing this heavily, it's not exactly hydejack anymore, right? Mind if it states "Built on Hydejack" instead?

**Comment by qwtel** [comment]
oh, just be aware that I'm still making *lots* of changes to the internals (not published yet) so upgrading will not be easy / you'll have to redo those changes. 

yes, in that case I'd prefer it if you mention it somewhere separately / change the wording. Thanks!

**Comment by SomuSysAdmin** [comment]
@qwtel that's pure genius bro! 
How did you even come up with a solution like that? I'm astounded!!

Also, since the site is being actively edited, it doesn't yet have everything that I'd like to be there. I will eventually credit everyone and every tech I've used.

**Comment by SomuSysAdmin** [comment]
@qwtel Cheers, bro - here's the credit, as promised: [At the very bottom!](https://www.somusysadmin.com/technologies/)
