### ISSUE TITLE
Is there a way to change the background color of inline code spans? 

### ISSUE THREAD

**Issue by SomuSysAdmin** [qwtel/hydejack#34]
@qwtel I'm talking specifically about the code generated between single ticks. Now, I've changed the `_syntax.scss` which changes the highlighting of the code blocks, but I wanna just change the background color of the text in single ticks. Is that possible? 

By investigating the CSS I've found that the `code` tag needs a certain background color and text color property in the CSS in _site folder. That's what I'm trying to achieve. What would be the best way to go about this? 

Thanks for all your help and hard work, man!

**Comment by SomuSysAdmin** [comment]
**NOTE** I can easily achieve this by adding the following lines to `/_sass/my-style.scss`, but I was wondering if there was a better/proper way?!

```css
code {
	background-color: #272822;
	color: #efefef;
}
```

**Comment by qwtel** [comment]
Nope that's fine actually. If you make it `pre` instead of `code`, it would only apply to block-level examples. 

File for changing the syntax theme:
https://github.com/qwtel/hydejack/blob/master/_sass/_syntax.scss
