### ISSUE TITLE
Project page displaying videos 

### ISSUE THREAD

**Issue by bioboot** [qwtel/hydejack#35]
I would like to use the project page layout to display screencast videos. 
Basically I want folks to be able to click on the displayed static image and let it play the video from Vimeo or youtube.

See: < https://bioboot.github.io/bggn213_f17/projects/welcome-screencast/ >

What would be the best way to do this beyond editing the `_layouts/project.html` as I don't want things to break with future updates. Maybe a new layout? What would you suggest?
Thanks!

**Comment by qwtel** [comment]
I think the safest/quickest solution would be to just embed the video in the markdown content below, using youtube's/vimeo's embed snippets.

the alternative would be to come up with a solution that is generic enough to be included in hydejack, but that would not be trivial.

**Comment by bioboot** [comment]
Got it thanks.  

One related issue with this approach is how to get around the pages sidebar interference when embedded videos are switched to playing full-screen.  

For example try playing the video here and then clicking the full screen option:  
https://bioboot.github.io/bggn213_f17/projects/welcome-screencast/

Any recommendations?
Thanks!

**Comment by qwtel** [comment]
Wrap the `iframe` inside a `div` with the `sixteen-nine`class and set `style="width:100%;height:100%;"` on the `iframe`.

This works when part of the regular content:

```html
<div class="sixteen-nine">
  <iframe src="https://player.vimeo.com/video/234066823" style="width:100%;height:100%;" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>
<p><a href="https://vimeo.com/234066823">01_welcome_BGGN213</a> from <a href="https://vimeo.com/grantlab">Barry Grant</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```
