### ISSUE TITLE
Random Sidebar Image

### ISSUE THREAD

**Issue by electricmessiah** [qwtel/hydejack#36]
I'd like to add an option to use a random sidebar image by adding something to the front matter. I messed around and was able to get the sidebar to be random if no front matter IMAGE was present by putting some code in the my-scripts under the "document.getElementById('_yPushState').addEventListener('y-push-state-start', function() , but it was missing out on the fade in animation. What would be the best way to achieve this?

**Comment by qwtel** [comment]
oh that's tricky. Going with JS is the right approach, but won't get around [transpiling the JS source code](https://qwtel.com/hydejack/docs/6.6.1/advanced/#building-the-javascript). You'll need some basic understanding of JS and [RxJS](https://github.com/reactivex/rxjs). Check out `_js/push-state.js` and `_js/cross-faders.js`. You'll need to include the list of all images in the output somewhere (or just hard-code in the JS source), then randomly provide it to `crossFader.fetchImage`. 

Also note that you'll have merge conflicts upgrading to upcoming versions of Hydejack...
