### ISSUE TITLE
Near perfect Google Page Speed not valid

### ISSUE THREAD

**Issue by martinschleiss** [qwtel/hydejack#39]
I'm using the same version as you are on my blog [schleiss.io](schleiss.io) and ran into the problem that Hydejack's CSS isn't minified as it is on your site. It's seems like you missed this one because you are using as a proxy. They use a feature called Auto Minify for on-site resources as explained here: [Source](https://support.cloudflare.com/hc/en-us/articles/200169876-Why-isn-t-Auto-Minify-working-)

My site: [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=schleiss.io&tab=desktop)
Your site: [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fqwtel.com%2Fhydejack%2F&tab=desktop)

**Comment by qwtel** [comment]
you need to have 

```yml
sass:
  style:               compressed
```

in your config file and not rely on things like auto minify.

**Comment by martinschleiss** [comment]
Ah thanks!

Now at 90/100 👍

**Comment by qwtel** [comment]
The bigger problem is the lack of caching I think. Cloudflare has an option for it somewhere, so that they are cached for ~8 days. Regular HTML pages will still have a 10min cache as defined by GitHub Pages.
