### ISSUE TITLE
Social links not displaying icons except github and twitter in gem-based theme

### ISSUE THREAD

**Issue by woahdae** [qwtel/hydejack#41]
Social links other than github and twitter show up as the "link" symbol instead of the expected email, stackoverflow, etc icon.

I've traced the problem as far as the theme (7.0.0) or Jekyll (3.6.2) not loading `site.data.social` nor `default:site.data_social` from the gem. If I copy `_data/social.yml` to my project directly, `site.data.social` is populated and everything works as intended.

Don't know about Jekyll's data loading mechanisms, obviously it works elsewhere since the `_data/strings.yml` looks to be there (by the fact that I see the strings).

**Comment by woahdae** [comment]
Correction, `site.data.strings` is also null, I was just seeing the hardcoded fallbacks.

**Comment by qwtel** [comment]
yes, this is as-intended. gem-based themes don't allow including the `_data` folder. I've hard-coded the two most common icons so the first-run experience is better, but I didn't what to hard-code all icons.
