### ISSUE TITLE
accent_color and accent_image have no effect

### ISSUE THREAD

**Issue by rriemann** [qwtel/hydejack#43]
Hello,

I installed hydejack according to the documentation using the gem method and copied the _config.yml from master.

My repo: https://github.com/rriemann/www.radio-blue.eu
online (via netlify): http://www.radio-blue.eu

Unfortunately, I **did not succeed to change the accent color**. Maybe this is due to the theme-mode.

I tripple-checked everything, but could not track down the problem. I also tried to set in e.g. about.md the accent_color explicitly and it did not have any effect.

**Comment by qwtel** [comment]
Hi,

your `Gemfile.lock` file suggests that you are using version 6.6.1, but the docs online and the config.yml you've copied are for 7.0.1 (you can access the [old docs](https://qwtel.com/hydejack/docs/6.6.1/) just in case). Running

    $ bundle update jekyll-theme-hydejack

should fix it. If that doesn't work, delete `Gemfile.lock` and run `bundle install`.

**Comment by rriemann** [comment]
An old Jekyll was actually preventing an update to the most recent theme version. Thank you for the pointer!
