### ISSUE TITLE
Feature idea: Comply with EU cookie law (get consent or track differently)

### ISSUE THREAD

**Issue by rriemann** [qwtel/hydejack#49]
Hello,

the template promotes a configuration of Google Analytics that requires consent which is usually acquired using a cookie consent banner.

https://github.com/insites/cookieconsent

Their website: https://cookieconsent.insites.com/demos/

Alternatively, some people change the google default tracking code to increase privacy so that no consent is required anymore:

https://www.themarketingtechnologist.co/setting-up-a-cookie-law-compliant-google-analytics-tracker/

It would be nice if one boolean value could be switched in the _config.yml to comply. :)

**Comment by qwtel** [comment]
I should do it. Soon-ish.

**Comment by rriemann** [comment]
Thank you for your work!

Two remarks on this.

1. the cookie banner does not allow to open the side menu on smartphones:

![image](https://user-images.githubusercontent.com/111932/33242095-acb814e6-d2cf-11e7-9537-3720f019e349.png)

2. Your template cookie policy is already quite extensive. Is it to cover US/EU/whatever law complience?

I think for the EU, you cannot enable Google Analytics before the banner has been accepted. When users visit the page the first time, it is already too late for them to opt-out.

**Comment by qwtel** [comment]
> Your template cookie policy is already quite extensive. Is it to cover US/EU/whatever law complience?

I did add the cookie policy by accident. not meant to be part of the release.

**Comment by qwtel** [comment]
reopend to make it opt-in

**Comment by rriemann** [comment]
I think it would be helpful to ship a cookie-policy that is compliant with US/EU. One could choose a text available under creative commons in the internet.

https://termsfeed.com/blog/sample-cookies-policy-template/

**Comment by qwtel** [comment]
that's actually where I got the policy from. however, since it was paid I'm pretty sure that I can't distribute it

**Comment by qwtel** [comment]
fixed in v7.4.1
