### ISSUE TITLE
Unable to install gems

### ISSUE THREAD

**Issue by akhilesh-k** [qwtel/hydejack#50]
Asks for password when I run command bundle install

Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password:

**Comment by qwtel** [comment]
Would you mind giving some more details? Is this something that could affect others, or just a bug unique to your situation? Thanks!

**Comment by akhilesh-k** [comment]
I got that.
