### ISSUE TITLE
First #Heading in a post is being taken as the post TITLE

### ISSUE THREAD

**Issue by ronamosa** [qwtel/hydejack#51]
just upgraded to PRO v7.4.2 and now having this issue.

what's happening is under my /blog/ section, any post which has ANY # heading right after the front matter is being listed as post title in the list of posts, and then when you click through, it is specified as that posts title.

e.g.
```
---
layout: post
title: ESXI 5.5 Free Version Reference Manual
description: >
  notes on keeping and runing a free esxi version which misses out on various functional/handy paid-for features. this will be an on-going document so I might pin it somewhere.
categories: [howto, infrastructure]
tags: [automation, esxi, vmware, ansible]
author: [ronamosa]
published: true
---

# Overview
this will be a work in progress and probably needs to be laid out, categorized better to be able to find stuff.
```

will list the post as "Overview", and the post heading on the article will also be "Overview", and the "title" will be nowhere to be found.

you can see it live here: https://ronamosa.github.io/blog/

funnily enough it works as expected when I run it locally with `bundle exec jekyll serve` but when pushed to GH pages only then do I see this issue. 

can you please advise which function might be responsible for doing this? can provide any other info you'd need for troubleshooting. thanks.

**Comment by qwtel** [comment]
Hm, that sounds like `jekyll-titles-form-headings` is at work. 
Can you check if this is listed in _config.yml? If yes, remove it.

Related: Are you hosting on GitHub Pages by any chance? If yes, this plugin is enabled by default there.
In this case add (or replace) to your config file

```yml
titles_from_headings:
  enabled: false
```

**Comment by qwtel** [comment]
Formatted:
```yml 
titles_from_headings: 
  enabled: false
```

**Comment by ronamosa** [comment]
Sorry for the delay! Just got around to trying this out and can confirm - this fixed my issue and posts are back to normal! Also confirming yes I am hosting on github pages! Thanks Florian, much appreciated.
