### ISSUE TITLE
Hydejack pro comments issue

### ISSUE THREAD

**Issue by UCSBGauchos** [qwtel/hydejack#53]
I enable the disqus: SHORTNAME and use comments: true for each of my posts md based on the document. But when I comment on one post, I can also see this post on another post. Is it possible to create different comment session for different post blog pages?  

For example, I have blog A and blog B. I write "test for A" below blog A. But I can also see this comment "test for A" below blog B. I thinks this is an issue.

**Comment by qwtel** [comment]
I've just reproduced it, and this is an issue with the page reloading. It works when you reload the page with F5. Until I fix this in an update, you can set 

```yml
hydejack:
   no_push_state: true
```
to disable the dynamic page loading.

**Comment by UCSBGauchos** [comment]
Thank you! Let me know when you fix it.
