### ISSUE TITLE
Will there be any update for search ability for the blog.

### ISSUE THREAD

**Issue by UCSBGauchos** [qwtel/hydejack#54]
Hi,

Just want to know is there any update plan for the search ability in the blog? For example, full text search for the blogs. 

Thanks

**Comment by qwtel** [comment]
Nope.

I was looking into it at one point, but decided against it.
The reasoning was this: I couldn't think of the last time I used somebody's on-page search functionality.

However, if you're still interested, you should look into Algolia.
