### ISSUE TITLE
[IDEA] Match a project's link to the project's respective accent color.

### ISSUE THREAD

**Issue by imswebra** [qwtel/hydejack#57]
Just an idea I had to clean up the design a little. I typically match a project page's accent color to be in line with the color of the project itself, as shown below.
![capture3](https://user-images.githubusercontent.com/29715203/34448329-7ce42fcc-eca9-11e7-9568-3395a38f732e.PNG)
This works beautifully and looks great, but when it comes to the links for an other project, the coherence is lost. The proposed idea is to have an option allowing links in the "Other Projects" section (and maybe also on the project overview page) to display their titles using the accent color of the project _that is being linked._ IMO this looks a lot nicer and would be a great addition. It would of course require the user to be diligent about defining accent colors manually, but the ability to enable / disable could mitigate anyone's troubles. See my quick photoshop mockups below:

**Original**
![capture](https://user-images.githubusercontent.com/29715203/34448262-f2368834-eca8-11e7-9595-18dd04ee120f.PNG)

**Proposed Idea**
![capture2](https://user-images.githubusercontent.com/29715203/34448263-f248f8d4-eca8-11e7-83e7-f9fb05c7893a.png)

**Comment by qwtel** [comment]
I had the same idea once, but decided against it because I thought it would end up way to colorful. I'll reconsider.

**Comment by qwtel** [comment]
I was giving this another shot, but there isn't a good way to give the underline the correct color, esp. considering that inline css doesn't allow hover styles.
