### ISSUE TITLE
Embedded Google Trends troubles.

### ISSUE THREAD

**Issue by imswebra** [qwtel/hydejack#60]
I'm having some bizarre problems with using an embedded Google Trends script. There seems to be two issues at play, one which I think relates to hydejack's use of dynamic loading. Note that the current version of my site has the problems fixed with `no_push_state` set to true, and using "raw" script tags.

*Here is the desired outcome, as can currently be seen [here:](http://www.imswebra.com/2017/07/04/flatearth)*
![desired](https://user-images.githubusercontent.com/29715203/34504192-35815b12-efda-11e7-9cb8-2647d8f413ba.PNG)
*Here is the base (raw) script:*
`<script type="text/javascript" src="https://ssl.gstatic.com/trends_nrtr/1243_RC12/embed_loader.js"></script> <script type="text/javascript"> trends.embed.renderExploreWidget("TIMESERIES", {"comparisonItem":[{"keyword":"flat earth","geo":"","time":"2012-06-20 2017-06-20"},{"keyword":"flat earth jokes","geo":"","time":"2012-06-20 2017-06-20"}],"category":0,"property":""}, {"exploreQuery":"date=2012-06-20 2017-06-20,2012-06-20 2017-06-20&q=flat%20earth,flat%20earth%20jokes","guestPath":"https://trends.google.com:443/trends/embed/"}); </script>`

**Problem 1) Script rendering as plain text**
When `no_push_state` is set to false, when using the raw script or using the script with `async`, and when testing locally (more on that later), everything works fine when loading the page directly via the page's URL. When you navigate to the page from somewhere else on the site however, you see the following. Note that refreshing the page fixes these issues.

*Broken Site:*
![error](https://user-images.githubusercontent.com/29715203/34504284-f5a68a3e-efda-11e7-8b2b-38c34e22ca34.PNG)
*Chrome Console:*
![error2](https://user-images.githubusercontent.com/29715203/34504295-03fc55c8-efdb-11e7-9d46-9d54c6415ac2.PNG)
*Chrome HTML:*
![error3](https://user-images.githubusercontent.com/29715203/34504306-167e519c-efdb-11e7-973d-2e94a4c87014.PNG)

Using `defer` works the same when loading from another part of the site, but when loading directly, the graph isn't shown at all, and the chrome console throws `Uncaught ReferenceError: trends is not defined at (index):244`.

I tried using hydejack's `loadJSDeferred` as well. Here's the code I used:
```
<script>
  loadJSDeferred('https://ssl.gstatic.com/trends_nrtr/1243_RC12/embed_loader.js', function () {
    trends.embed.renderExploreWidget("TIMESERIES", {"comparisonItem":[{"keyword":"flat earth","geo":"","time":"2012-06-20 2017-06-20"},{"keyword":"flat earth jokes","geo":"","time":"2012-06-20 2017-06-20"}],"category":0,"property":""}, {"exploreQuery":"date=2012-06-20 2017-06-20,2012-06-20 2017-06-20&q=flat%20earth,flat%20earth%20jokes","guestPath":"https://trends.google.com:443/trends/embed/"});
  });
</script>
```
Interestingly enough, this kinda works, but the graph is the only element on screen, scaled to be the full width of the window. Looking into the HTML, it *is* the only element; Hydejack did not load at all. As such, no errors occur.

Again, setting `no_push_state` to false fixes the weird script showing up as plain text, and therefore fixes the graph when using `async` or the raw script. It does not fix the graph not loading when using `defer` and does not fix the graph being the only element when using `loadJSDeferred`. 

**Problem 2) Embedded graph not showing up.**
When I first committed the page on which I am using the script, I had `no_push_state` set to true, and had the script code as follows:
```html
<script async type="text/javascript" src="https://ssl.gstatic.com/trends_nrtr/1243_RC12/embed_loader.js"></script> <script async type="text/javascript"> trends.embed.renderExploreWidget("TIMESERIES", {"comparisonItem":[{"keyword":"flat earth","geo":"","time":"2012-06-20 2017-06-20"},{"keyword":"flat earth jokes","geo":"","time":"2012-06-20 2017-06-20"}],"category":0,"property":""}, {"exploreQuery":"date=2012-06-20 2017-06-20,2012-06-20 2017-06-20&q=flat%20earth,flat%20earth%20jokes","guestPath":"https://trends.google.com:443/trends/embed/"}); </script>
```
Notice the double use of `async`. Running the page locally works as expected, however, when the page was built by GitHub after committing and pushing the changes, the live, online version of the page did not show the embedded graph at all. Removing `async` from the second `<script>` does not change anything, but removing both `async` attributes, leaving the script raw, fixes the issue. I did not have time to really investigate nor conduct further tests, but I believe the error was something to do with "trends", similar to the error received when using `defer`. I'm quite curious as to why there was a difference between running the page locally and running it online, and I can't confirm that this is a Hydejack issue.

**Question:**
Is there a better solution to this problem besides setting `no_push_state` set to true and using the raw script?

**Comment by qwtel** [comment]
I've debugged this and found the issue. 

However, now the embed script seems to get stuck in an endless loop when loading it twice. It's just one of those scripts not meant to be used in this way. Stick to `no_push_state:true` or maybe take a screenshot of the graph
