### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by MaxShalom** [qwtel/hydejack#63]
@qwtel 
How can I change or delete the favicon?

**Comment by MaxShalom** [comment]
I didn't see it in the documentation. 
Can anyone help me?

**Comment by qwtel** [comment]
Unfortunately the docs are not up-to-date in that respect.

It needs to be placed in `/assets/icons/favicon.ico`

**Comment by rishabkdoshi** [comment]
@qwtel , this didnt work for me? Has something changed?

My git repo is here: https://github.com/rishabkdoshi/rishabkdoshi.github.io

**Comment by qwtel** [comment]
* Clear browser cache
* Favivon appears to be big? Should be ~32x32
* Use latest version, change `remote_themem` to `qwtel/hydejack@v8.1.1`

**Comment by rishabkdoshi** [comment]
@qwtel , Thank you for the response. But doing both didn't work. The favicon used is still the default one.

**Comment by qwtel** [comment]
it’s the cache this time

**Comment by rishabkdoshi** [comment]
that worked, thanks
