### ISSUE TITLE
Is the {:.readmore} (i.e., `.read-more` class) a hyddejack exclusive, or something originating from kramdown or jekyll?!

### ISSUE THREAD

**Issue by SomuSysAdmin** [qwtel/hydejack#64]
I'm extremely intrigued by it, and would like to see how you coded it. But for some reason, I can't find any of it's contents. Can you please tell me where it's javascript/CSS/etc (all kinds of code related to `.read-more` are located?! Thanks!!

**Comment by SomuSysAdmin** [comment]
Note: I have found several mentions of it, but I'd like to know if this is all there is to it?!

~~~console
$ grep -rE '.read-more' *
docs/7.5.0/basics.md:{:.read-more}
docs/7.5.0/build.md:{:.read-more}
docs/7.5.0/config.md:{:.read-more}
docs/7.5.0/install.md:{:.read-more}
docs/7.5.0/scripts.md:{:.read-more}
docs/7.5.0/upgrade.md:{:.read-more}
docs/7.5.0/writing.md:{:.read-more}
_includes/post.html:      <p class="read-more">
_sass/pooleparty/__link/_type.scss:.read-more {
_sass/pooleparty/_type.pre.scss:.read-more {
~~~

**Comment by SomuSysAdmin** [comment]
Also, what does `.flip-title` do, and where can I find its related code?

**Comment by qwtel** [comment]
.read-more is just a CSS class, located in _sass/pooleparty/_type.pre.scss. It has nothing to do with either jekyll or hydejack.
.flip-title marks a link for the title animation. This should be applied to links that have the same text as the page they link to.
The related code is in _js/src/flip/title.js

Cheers,
Florian
