### ISSUE TITLE
Docusaurus

### ISSUE THREAD

**Issue by MaxShalom** [qwtel/hydejack#66]
Hey, 
The documentation is great, however, I stumbled upon this project and think it would be a perfect fit.

**Docusaurus** is a project made by Facebook that helps you make:

> "Easy to maintain open source documentation websites." 

The docs for Hydejack would be written in Markdown, so importing wouldn't be hard, and the site would be customizable through React. You can see the website [here](https://docusaurus.io). In addition, it works with Github Pages which should be great (according to [this post](https://docusaurus.io/docs/en/publishing.html#using-github-pages) on their website).

See it on Product Hunt: https://www.producthunt.com/posts/docusaurus

If you think it would work for this project, I'd love to help out. 
Let me know.

**Comment by MaxShalom** [comment]
Any update? 

Not sure if Docasuarus would be good for this project, but it looks great.

**Comment by qwtel** [comment]
I believe in dogfooding, and it would send the wrong signals if Hydejack was documented using anything other than Hydjeack.

Docusaurus looks good though.
