### ISSUE TITLE
Pagination: Pagination is enabled, but I couldn't find an index.html

### ISSUE THREAD

**Issue by bekircem** [qwtel/hydejack#68]
Hi,

I read theme docs. I made everything as it should be. I want to see post with excerpts in homepage. 

https://qwtel.com/hydejack/docs/7.5.0/config/#choosing-a-blog-layout

I added paginate block in the gem file and install it. I created index.html file.

When i use bundle exec jekyll serve, it gives me error.

`Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.`

 Homepage opened empty with that string: `# file: index.html --- layout: blog title: Blog ---`

**Comment by qwtel** [comment]
Remove the comment

```yml
---
layout: blog
title: Blog
---
```

**Comment by bekircem** [comment]
I removed coment but layout does not change. It still seems list layout not a blog.
