### ISSUE TITLE
Content overflowing on the right hand side!

### ISSUE THREAD

**Issue by SomuSysAdmin** [qwtel/hydejack#69]
Hey, I was using an older version of hydejack in which the page was bounded on the right hand side, and elements maintained a margin to the right. This can be demonstrated by the image below:

![Old Version Display](https://i.imgur.com/cxl3Pjd.png)

Now in the present version, the tables and code overflow on the right hand side!

![New Version -- elements overflowing to the right! ](https://i.imgur.com/WkDjkRV.png)

 How do I stop this behavior and bring it back to the state of the original above?

**Comment by SomuSysAdmin** [comment]
I'm sorry but why the overflow? And why does it make the page look so ugly?! Is it because I'm viewing on a laptop with a low resolution?!

**Comment by SomuSysAdmin** [comment]
And is there a way I could control the right margin?!

**Comment by qwtel** [comment]
Sorry you don't like the new layout. 

In your config file, set:

```yml
hydejack:
  no_break_layout: true
```

I personally prefer new layout. If you put yourself in your reader's shoes, would you like to scroll horizontally every time you encounter a large code block / table, even when there is plenty of space to the left?

This is a trade-of between conceptual design beauty and putting readers first, and I went with the later.
