### ISSUE TITLE
Is there a way to increase the margin in the right side of the page in the new layout?!

### ISSUE THREAD

**Issue by SomuSysAdmin** [qwtel/hydejack#70]
Hey, this is in regards to #69 :

While the page's margin overflow is fixed by your suggestions, I was wondering, if I wanted to fix the amount of space that'll be used when the following is used?!

~~~markdown
hydejack:
  no_break_layout: true
~~~

As you suggested, the old layout wasted too much space in the right and the new layout doesn't leave enough space when viewed in the browser. Is there a way i can manually set the amount of space to the right? It's okay even if I have to edit a few files. Just point me in the right direction?!

**Comment by qwtel** [comment]
Basically, no.

I'm glad I found a CSS only solution, but it is not easy to understand: https://github.com/qwtel/hydejack/blob/master/_sass/hydejack/_break-layout.pre.scss
