### ISSUE TITLE
Double Title

### ISSUE THREAD

**Issue by MaxShalom** [qwtel/hydejack#71]
On my site using Hydejack, I have the following as the heading:

> ```
> ### Learning AP Computer Science A - Java
> ```

and I get the following: 

![image](https://user-images.githubusercontent.com/23295246/35484350-c23ca326-041c-11e8-99ce-154c5df5e3cb.png)

I tried adding 
```
---
layout: page 
title:  Learning Computer Science A - Java
--- 
```
but, that resulted in a `404 - file not found` I think because it is the home page.

Why is it that I have a double title and how can I fix that?

See what I mean [here](maxshalom.me/ap-java/).

@qwtel

**Comment by qwtel** [comment]
I assume this only happens on GitHub Pages? Then it is probably related to [`jekyll-titles-from-headings`](https://github.com/benbalter/jekyll-titles-from-headings). You could change the settings to get the behavior you want:

```yml
titles_from_headings:
  enabled:     true
  strip_title: true
```

**Comment by MaxShalom** [comment]
Would that go in _config.yml?

**Comment by qwtel** [comment]
Yes. Note that you might have change the options to fit your needs. The above would set the page title to "Learning AP Computer Science A - Java" and remove the h3 from the document.

**Comment by MaxShalom** [comment]
Thank you, I will do that and let you know if it works.
On Feb 12, 2018 at 2:47 PM, <<notifications@github.com>Florian Klampfer> wrote:
Yes. Note that you might have change the options to fit your needs. The above would set the page title to "Learning AP Computer Science A - Java" and remove the h3 from the document.

**Comment by qwtel** [comment]
Reopen if necessary
