### ISSUE TITLE
getting error Invalid US-ASCII character

### ISSUE THREAD

**Issue by neidiom** [qwtel/hydejack#72]
Any idea why?

```
      Generating... 
      Remote Theme: Using theme qwtel/hydejack
  Liquid Exception: Liquid error (line 1): Invalid US-ASCII character "\xE2" on line 155 in assets/css/hydejack-7.5.0.css
jekyll 3.6.2 | Error:  Liquid error (line 1): Invalid US-ASCII character "\xE2" on line 155
```

**Comment by qwtel** [comment]
I think this is something related to character encodings. Does your editor default to ASCII instead of UTF-8? Did you modify any files in `_sass`?

To be save, you could go through the files and remove all the non-ASCII characters (they only show up in comments, e.g. `content: " \2192"; // →`

**Comment by agent-reed** [comment]
Yup.  This is the case in the following files:

*_sass/pooleparty/__link/_posts.scss* -    `content: "\2756"; // ❖`
*_sass/pooleparty/__link/_type.scss*   -    `content: " \2192"; // →`

Removing the comments fixes the issue in scenarios when deploying Hydejack with Docker, Azure, Werker, etc.

**Comment by qwtel** [comment]
Thanks for updating me on this. I've removed them in the source (quite an unnecessary bug, actually), will be included in some future update.
