### ISSUE TITLE
redirect_to: in a post throws an error "jekyll 3.6.2 | Error:  can't modify frozen String"

### ISSUE THREAD

**Issue by alecsatin** [qwtel/hydejack#73]
Have just about completed a migration to hydejack from another Jekyll theme.   Post redirects in the yaml such as
```
redirect_to: /some/location/
```
will not work.  I've used jekyll-redirect-from before without any issue.  Any help appreciated.

**Comment by alecsatin** [comment]
# Work around
Since the site builds and deploys correctly *except* on my local development environment, I used a _config-dev.yml to exclude the post triggering the "can't modify frozen string" error.  There's likely something wrong with my ruby installation or my Gemfile.lock, but I don't know enough about ruby and/or bundler to fix it.

In case anyone comes across this issue in future, here are the steps to "work-around":

Create a _config-dev.yml file such as this:
```
url: "http://localhost:4000"
exclude:
  - _posts/2010-01-01-feed-redirect.md
```
Develop locally with bundle using the --config option such as:
```
bundle exec jekyll serve --config _config.yml,_config-dev.yml
```

Would love to find a real solution, so if anyone has anything to add, it would be appreciated.  Otherwise it's working for now.

**Comment by qwtel** [comment]
that is an odd issue, but I'm not sure what to do about it, or even how to reproduce.  I use `jekyll-redirect-from` too, and it works fine both locally and remotely. I'm going to close this issue for now
