### ISSUE TITLE
doc enhancement: new way to install hydejack on github

### ISSUE THREAD

**Issue by rriemann** [qwtel/hydejack#74]
Hello,

github pages allows now to use remote templates hosted on github. So with `remote_theme: qwtel/hydejack` it should also be possible to use this theme without forking its entire source.

:)

More: https://github.com/blog/2464-use-any-theme-with-github-pages (November 29, 2017)

**Comment by qwtel** [comment]
This is already the recommended way of installing Hydejack: https://qwtel.com/hydejack/docs/7.5.0/install/#via-starter-kit :)

Repo: https://github.com/qwtel/hydejack-starter-kit/
