### ISSUE TITLE
The page build failed for the `master` branch with the following error:  Page build failed.

### ISSUE THREAD

**Issue by VernonLD** [qwtel/hydejack#75]
I have problem about building my GitHub pages. I could run my website on my localhost but I always got a problem when I push the repository into GitHub and build my GitHub page. I followed the steps from the document and I still got this failure. Could you help me with this?

**Comment by qwtel** [comment]
sorry, I don't provide free support. if you can build the site locally (i.e. `jekyll build`) you can push the HTML files to github pages. no cloud-build required.
