### ISSUE TITLE
bug: some arrow icon appears in Firefox app mode on Android

### ISSUE THREAD

**Issue by rriemann** [qwtel/hydejack#76]
Next to the hamburger button to show the sidebar on Android phones, there is an arrow icon. It sticks to the corner when scrolling.

Reproduction:

- go to https://github.com/rriemann/cast-writing with Firefox Mobile on android
- click the house button in the url bar to add this website as an app to the homescreen
- find the app on the homescreen, start the app and notice the arrow icon

![android](https://user-images.githubusercontent.com/111932/36207029-cb5fa96e-1194-11e8-98e2-e3fdc1d86507.png)

**Comment by qwtel** [comment]
This is a feature, not a bug. When using the site in standalone mode (without the browser bar at the top, as in the screenshot) Hydejack adds a back button, as it's not possible to go back otherwise.

**Comment by rriemann** [comment]
OK. My Android phone has a back button, but I guess the iPhone has not.
