### ISSUE TITLE
[Bug]: Gists with maps do not load when loading content with y-push-state

### ISSUE THREAD

**Issue by rriemann** [qwtel/hydejack#77]
I embed via jekyll-gist a gist that is a geojson file which github renders as a map. When I navigate to such a post, I only see plain html code.

## Reproduction

1. go to https://blog-riemann.netlify.com/travels/
2. click on first link (Romania) to navigate to https://blog-riemann.netlify.com/travels/2015/07/08/impressions-from-romania/
3. find html garbage instead of map
4. press now F2 to reload page.
5. find map instead of html garbage.

I think the problem is related to y-push-state.

**Comment by qwtel** [comment]
I remember fixing this issue a while ago, but ended up not shipping it for some reason (I think it crashed chrome in one instance). It works on my working copy of hydejack 8 though.

Generally, scripts that use `document.write` don't blend well with the dynamic page loading approach of `hy-push-state` (renamed from `y-push-state`). The cleanest solution is to disable push state by adding to the `hydejack` key in `_config.yml`

```yml
hydejack:
  no_push_state: true
```

**Comment by qwtel** [comment]
This should be fixed in 7.5.1
