### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by botev** [qwtel/hydejack#80]
Hi,

First thanks a lot for this Jekyll Theme I really like it and it was great pleasure exploring its capabilities. Also given that my blog is going to be relatively mathsy the default integration with latex rendered (via Katex).

I added a few very very tiny things to my blog and if you do think any of them would be of interest I would be happy to make a PR for them. Here is a list:

* Adding a switch/flag for whether to display the author "about" at the end of each post. I personally find it a bit too much and preferred to keep that info only on the about page. 

* Adding a `sidebar_picture` to the authors' data to allow for an avatar in the sidebar. Currently, it is set to expect a picture with 3:4 ratio (e.g. vertical). Here you can see how it looks: https://botev.github.io/

* I've added one more icon to the default ones (`books` from the default Icomoon) and added a `scholar` social referring to Google Scholar. 

* As discussed in #14 I've added a flag for displaying the page on load. This includes adding to `my-scripts.js` the following code:
```
{% if  site.fout_removal %}
  <script>
    document.body.style.visibility = 'hidden';
    function makeBodyVisible() { document.body.style.visibility = 'visible'; }
    if (window.addEventListener) window.addEventListener("load", makeBodyVisible, false);
    else if (window.attachEvent) window.attachEvent("onload", makeBodyVisible);
    else window.onload = makeBodyVisible;
  </script>
{% endif %}
```

**Comment by qwtel** [comment]
Hi,

thanks for reaching out, I'm always interested in how people use and customize hydejack.

Regarding your points: 
1. is already achievable with the `post_addons` and `project_addons` configuration option 🙂 (see example config).
2. sidebar images are great. I've already implemented them in the [upcoming v8 version](https://qwtel.com/hydejack-dev/) (using the config `logo` key, also used by `jekyll-seo-tag`)
3. Yes! I should add more icons for academic platforms (not sure what the most important ones are though. google scholar. researchgate? arxiv?)
4. It's okay if you configure your page in this way, but I'm categorically opposed to it. I recognise that it is rather ugly and I've made some changes to it in v8, but the basic principle stays the same.

**Comment by botev** [comment]
Cool, I will be looking forward to the logo in v8. I need to check regarding `post_addons` and see how to then achieve the same. 

As for the research platforms, at least in my area (Machine Learning) Google Scholar and arxiv are the most popular. Google scholar as a platform to showcase all work, while arxiv is great because it's a free open venue for publications. 

And thanks for getting back so fast.
