### ISSUE TITLE
[Question] How do I show more than 5 links in the "Pages" section at the bottom of my homepage?

### ISSUE THREAD

**Issue by austinhuang0131** [qwtel/hydejack#82]
I'm not using blog layout (The site is not a blog).

[Repo](https://github.com/austinhuang0131/austinhuang0131.github.io)

Also I do want to say that your theme is awesome.

**Comment by qwtel** [comment]
The `home` layout was only meant to make the first-run experience of using the theme with an empty Jekyll project a bit more interesting, so there are no configuration options.

If you really need to make a change, you need to open [`_layouts/default.html`](https://github.com/qwtel/hydejack/blob/master/_layouts/default.html) and look for 

```html
{% for page in pages limit:5 %}
```

If you are using the gem-based theme or the starter pack you need to create the `_layouts` folder and copy `default.html` first. Note that this will overwrite Hydejack's own `default` layout, so be careful when you update.
