### ISSUE TITLE
No ssh key in zip file (pro)

### ISSUE THREAD

**Issue by StuartMorrisAU** [qwtel/hydejack#83]
Hi there,

I bought the pro version, however the zip file I downloaded does not contain the .ssh folder with the GitHub key.

**Comment by qwtel** [comment]
I've sent it to the mail you've used for purchase. Will fix soon.

**Comment by StuartMorrisAU** [comment]
No worries, thanks. 👍

**Comment by shawnyeager** [comment]
Just purchased, and was about to post the same. Please send to me as well. Email address used to purchase will match my github username. Thanks.

**Comment by qwtel** [comment]
This should be resolved now (together with a couple of other issues with the packaging of the zip). Thanks for reporting this.
