### ISSUE TITLE
Upgrade Path

### ISSUE THREAD

**Issue by mergesort** [qwtel/hydejack#88]
Hi @qwtel. Thanks for all the hard work, your Hydejack fork has been my favorite blog theme to use.

I was looking to upgrade my blog and get the fixes in 7.5.x. I've made configuration modifications, added posts, etc, and was wondering if there was a list of what files I should modify to upgrade the blog without losing data.

Thanks again!

**Comment by qwtel** [comment]
Unless you've modified the source, the best way would be to use either the gem-based version or  jekyll-remote-theme version (example here: https://github.com/qwtel/hydejack-starter-kit).

I think it's safer to take your posts, assets and possibly config to a new hydejack setup, rather then the new hydejack files to the old folder.

**Comment by mergesort** [comment]
I must have missed that, I just took the release version when I first installed and ran with that.

Thanks for the information!
