### ISSUE TITLE
GDPR compliant analytics

### ISSUE THREAD

**Issue by rriemann** [qwtel/hydejack#89]
Hello,

can we together make it more easy for hydejack deployments to reach GDPR compliance?

The cookie-banner is a very good start. I would like to suggest to add:

1. review current google analytics settings
2. make it easy to use alternative first-party analytics software, such as matomo that can be installed on premise.

For reference, this PR implements for another jekyll theme anonymization of IP addresses:
https://github.com/mmistakes/minimal-mistakes/pull/1636/files

Things we should check:
- is DNT header respected? (automatically respected by matomo, but maybe not by google)
- split google code into separate file and allow for other files (similar to <https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/analytics.html>)
- hydejack uses localstorage insead of cookie to save consent. This way, there is no expiration date. I think the consent should not be given forever, but should expire at some point.

My code for matomo (to be checked):

```liquid
{% if site.matomo_analytics %}
  <!-- Matomo -->
  <script type="text/javascript">
    var u="{{site.matomo_analytics.root}}";
    var _paq = _paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    {% if site.matomo_analytics.no_cookies %}
    _paq.push(['disableCookies']);
    {% endif %}
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '{{site.matomo_analytics.site_id}}']);

    loadJSDeferred(u+'piwik.js');

    var timeStartLoadPage, referer, timeItTookToLoadPage;
    document.getElementsByTagName('hy-push-state')[0].addEventListener('hy-push-state-start', function() {
      timeStartLoadPage = new Date().getTime();
      referer = window.location.toString();
    });

    document.getElementsByTagName('hy-push-state')[0].addEventListener('hy-push-state-ready', function() {
      timeItTookToLoadPage = new Date().getTime() - timeStartLoadPage;
    });

    document.getElementsByTagName('hy-push-state')[0].addEventListener('hy-push-state-after', function() {
      _paq.push(['setReferrerUrl', referer]);
      _paq.push(['setCustomUrl', window.location.toString()]);
      _paq.push(['setDocumentTitle', document.title]);
      _paq.push(['deleteCustomVariables', 'page']);
      _paq.push(['setGenerationTimeMs', timeItTookToLoadPage]);
      _paq.push(['trackPageView']);
    });
  </script>
  <!-- End Matomo Code -->
{% endif %}
```

**Comment by qwtel** [comment]
Okay, let's do this.

> is DNT header respected? (automatically respected by matomo, but maybe not by google)

It does not. Still unsure wether to include http://www.outfox.com/do-not-track-for-google-analytics/

> split google code into separate file and allow for other files (similar to https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/analytics.html)

I agree that analytics solution should be pluggable. On my development branch (not public) I've implemented it the same way as I did the newsletter. Default is Tinyletter (Google Analytics). however if you add custom code to `_includes/my-newsletter.html` (`_includes/my-analytics.html`), the default will be overwritten. Example code in `my-analytics.html` will be matomo. I've used your code snippet and assume that it works.

> hydejack uses localstorage insead of cookie to save consent. This way, there is no expiration date. I think the consent should not be given forever, but should expire at some point.

Now using a JS cookie to set cookie consent.

***

**Disclaimer**: Fundamentally it is the responsibility of site owners to comply with any laws that might apply in a given jurisdiction. Anything Hydejack provides is a voluntary bonus that comes without any guarantees, *especially* no legal ones!

> review current google analytics settings

See above.

> make it easy to use alternative first-party analytics software, such as matomo that can be installed on premise.

Will be possible with the coming release.

This issue will close once I merge the development branch.
