### ISSUE TITLE
Autohide Sidebar

### ISSUE THREAD

**Issue by rahulpathakml** [qwtel/hydejack#90]
Hi Florian, Thank you for a beautiful theme!

How can I make sidebar to autohide sidebar after few seconds. If not automatic, I can use a button on the top left which can make sidebar to appear/hide.

Reason of why I am asking is that, I have rotated my monitor in portrait mode and on that the content area is appearing less with sidebar.

![screenshot from 2018-05-16 11-44-02](https://user-images.githubusercontent.com/23165276/40099730-d9b30df6-58fe-11e8-805d-172bc2cf09ca.png)

I also bought the pro version but nothing downloaded. From where i can download the zip file 

Thanks
Rahul

**Comment by qwtel** [comment]
No such feature is currently planned. You'd have to dig into the code yourself to implement this, but I can't guarantee that it will work.
