### ISSUE TITLE
Multiple resumes

### ISSUE THREAD

**Issue by mberglundmx** [qwtel/hydejack#91]
Is it possible to have multiple resumes? I don't see any way to specify the jsonresume in the front matter.

**Comment by qwtel** [comment]
Currently it's not possible. I was wondering if that use case would ever come up. Making changes to `_layouts/resume.html` shouldn't be too difficult though.

**Comment by mberglundmx** [comment]
Ok, I'll give it a try - we are planning on using your theme for our corporate web, and there we present all consultants' cv's.

**Comment by mberglundmx** [comment]
It was easy to solve, I just set the resume to use in the front matter, and update:

{% assign resume = site.data.[page.resume] %}

Works, so solved for me.

**Comment by qwtel** [comment]
Please keep in mind that hydejack comes without warranties and is distributed AS-IS. It is by design intended to be used for personal websites, not business, corporate, etc.
