### ISSUE TITLE
Incorrect URL when sharing from Mobile Safari

### ISSUE THREAD

**Issue by mergesort** [qwtel/hydejack#92]
This bug is a bit subtle, so I'll try to recreate it step by step:

This is reproducible with any URL, but for sake of simplicity, let's use this one: `https://fabisevi.ch/2018/05/15/fifteen-minute-meetings/`

#### Working case
If I navigate to this page on Mobile Safari directly, when I try to share using Safari's built in sharing mechanism, everything works correctly.

#### Failing case
If I start on the homepage and tap the top link (the same URL), the URL bar changes to `https://fabisevi.ch/2018/05/15/fifteen-minute-meetings/` as expected. But when I try to share using Safari's built in sharing mechanism, it copies the homepage to the clipboard.

I suspect this has to do with how navigation is handled on the JavaScript side, but I am not a knowledgeable enough web developer to figure out how come.

If you need any more information, I'm happy to provide more.

Thanks a lot!

**Comment by qwtel** [comment]
Thanks for reporting this.

Yes, this is almost certainly due to how iOS Safari handles the History API. Interestingly, it works correctly in macOS Safari. Will try to reproduce on iOS later. But this is probably an issue with iOS Safari, not something I can fix.
