### ISSUE TITLE
A generated page displays Error but reloads after refreshing consistently

### ISSUE THREAD

**Issue by summations** [qwtel/hydejack#94]
I am getting this issue consistently. I have added a new directory "snippets" which has markdown files in it.These markdown files are indexed in another markdown "index.md" which is present at the root level.

Issue is that when I try to open any link whose markdown is present in the "snippets" directory. It displays error in the starting "Sorry, an error occurred while loading" But then after pressing F5, it works. This happens always.

https://summations.github.io/snippets/    This link has the index of links which are present in the snippets directory. 

Please let me know if something is not clear. I really need your help

**Comment by qwtel** [comment]
the component can’t donredirects, you need to like to the exact `permalink`, i.e. with the trailing `/`
