### ISSUE TITLE
Social buttons in sidebar

### ISSUE THREAD

**Issue by hsnee** [qwtel/hydejack#95]
Is there an easy way to do this? I have already filled in author-info in both _config.yaml and _data/authors.yaml as well as some social links/usernames.

**Comment by qwtel** [comment]
Maybe you forget to restart jekyll after making chagnes to `_config.yml`?

**Comment by hsnee** [comment]
is there anything other than `bundle exec jekyll serve` to do?

**Comment by hsnee** [comment]
One thing I'm confused about that might be causing this: in `_config.yml`, it says the author should be duplicated from `_data/authors.yml`. Should I just copy and paste it from there? Should the one in `_config.yml` start with `author: ` or the shorthand I used in `_data/authors.yml`

**Comment by hsnee** [comment]
Actually, looking through my browser inspector (screenshots in attachment), it does look like they were set up correctly, but still not shown for some reason 
<img width="656" alt="screen shot 2018-06-24 at 11 37 42" src="https://user-images.githubusercontent.com/12966709/41818276-30871628-77a3-11e8-89aa-d2683b2996f8.png">
<img width="1129" alt="screen shot 2018-06-24 at 11 35 39" src="https://user-images.githubusercontent.com/12966709/41818277-309fd7a8-77a3-11e8-898e-d88896fe5bba.png">

**Comment by hsnee** [comment]
OK it looks like the problem is only with safari -- any fix?

**Comment by hsnee** [comment]
OK it looks like my adblocker is blocking them. Any reason they are being identified as ads/any way around this?

**Comment by rriemann** [comment]
Normally your adblocker comes with an anaylisis tool that shows all blocked items and based on which rules those items were blocked.

**Comment by qwtel** [comment]
hm, maybe because of the CSS class name `sidebar-social`. Would be interesting if the issue persists after a rename.

**Comment by qwtel** [comment]
going to close this for now
