### ISSUE TITLE
Incorrect labelling of projects with blank description (works locally)

### ISSUE THREAD

**Issue by Zylatis** [qwtel/hydejack#96]
I have project pages where there is no description tag in the .md file because I didn't want that grey box showing.

However, this seems to have messed with what is shown on the projects.md page, where it seems to take the next heading and use that as the descriptor - so basically all of the projects have a title 'summary', as shown here

https://zylatis.github.io/projects/

This doesn't seem to happen on the local version.

An example header code is:

layout:       project
date:         01 Jan 2018
title:        PBS Spacetime
caption:      Science!
image:        /assets/img/3.png
screenshot:
  src:        /assets/img/3.png
  srcset:
    1920w:    /assets/img/3.png
    960w:     /assets/img/3.png
    480w:     /assets/img/3.png
links:
accent_color: '#4fb1ba'
accent_image: /assets/img/scot_myst_crop.jpg

Below which is the summary heading, which when I include here seems to get parsed and bolds everything so i left it out (as evidenced in the hilarious edit history for this post!)

Thanks,
G.

**Comment by qwtel** [comment]
Try `hide_description: true` instead. Not sure if this is inlcuded in 7.5.1 though

**Comment by Zylatis** [comment]
No bueno :( I made the change, still works locally but not on gitpages.

https://github.com/Zylatis/zylatis.github.io/edit/master/_projects/Tcells.md
https://zylatis.github.io/projects/

Is there an update I need to apply? (sorry if stupid question)

Thanks,
G.

**Comment by qwtel** [comment]
Ahh, this is related to the `jekyll-titles-from-headings` plugin that's enabled on GH pages by default. You can disable it in your `_config.yml` by setting:

```yml
titles_from_headings:
  enabled: false
```

You can also remove it from the list of `plugins` in your config file and the `Gemfile` as well.

**Comment by Zylatis** [comment]
Ah perfect, thanks! All sorted.
