### ISSUE TITLE
how to remove document menu from sidebar(pro)

### ISSUE THREAD

**Issue by shinhj0728** [qwtel/hydejack#97]
Hi qwtel.
Thank you for the great work!

How can I remove document menu?
I couldn't find the manual for configuration.

**Comment by shinhj0728** [comment]
Hi qwtel.

I delete docs folder.

but the document menu is still exist.

![image](https://user-images.githubusercontent.com/8906455/42122351-6882822e-7c7b-11e8-862e-f12ad3f1e56f.png)

**Comment by qwtel** [comment]
please reopen if restarting jekyll didn't resolve the issue

**Comment by shinhj0728** [comment]
It seemed that I needed some time to get the changes to take effect.

Thanks
