### ISSUE TITLE
/posts/ no longer builds correctly

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#99]
While everything else builds as expected, [/posts/](https://shawnyeager.com/posts/) now produces a page with no posts listed. Any known issues with the current version of jekyll (3.8.3) or ruby 2.5.1?

**Comment by qwtel** [comment]
I remember getting this on my own site after upgrading Jekyll. I was using liquid templates in a weird way, so not really a bug with Jekyll. I'll ship a fix for the v7 track.

**Comment by shawnyeager** [comment]
For anyone else having this problem, (not surprisingly) reverting back to the original `Gemfile.lock` solves it.
